#!/bin/bash
# Generated by vim-plug
# Tue 02 Dec 2014 10:33:24 PM PST

vim +PlugUpdate +qa

PLUG_HOME=~/.vim/plugged

cd $PLUG_HOME/auto-pairs/ && git reset --hard c2f60ca
cd $PLUG_HOME/clang_complete/ && git reset --hard f241549
cd $PLUG_HOME/ctrlp.vim/ && git reset --hard b5d3fe6
cd $PLUG_HOME/gist-vim/ && git reset --hard d609d93
cd $PLUG_HOME/gundo.vim/ && git reset --hard 3975ac8
cd $PLUG_HOME/lightline.vim/ && git reset --hard 6f71e12
cd $PLUG_HOME/neocomplcache.vim/ && git reset --hard f1ee320
cd $PLUG_HOME/promptline.vim/ && git reset --hard 29608bc
cd $PLUG_HOME/rainbow_parentheses.vim/ && git reset --hard 229cc12
cd $PLUG_HOME/supertab/ && git reset --hard b0ca47f
cd $PLUG_HOME/syntastic/ && git reset --hard 67ffe58
cd $PLUG_HOME/tabular/ && git reset --hard 60f2564
cd $PLUG_HOME/tcomment_vim/ && git reset --hard 30bb1f8
cd $PLUG_HOME/tmuxline.vim/ && git reset --hard 1e638ef
cd $PLUG_HOME/vim-bookmarks/ && git reset --hard 3d4aded
cd $PLUG_HOME/vim-colors-solarized/ && git reset --hard 528a59f
cd $PLUG_HOME/vim-easymotion/ && git reset --hard ca1bb25
cd $PLUG_HOME/vim-fugitive/ && git reset --hard 2c8461d
cd $PLUG_HOME/vim-gitgutter/ && git reset --hard 57342e3
cd $PLUG_HOME/vim-multiple-cursors/ && git reset --hard 35028be
cd $PLUG_HOME/vim-opinion/ && git reset --hard 6630a30
cd $PLUG_HOME/vim-rsi/ && git reset --hard ec39927
cd $PLUG_HOME/vim-sensible/ && git reset --hard 64aa12b
cd $PLUG_HOME/vim-surround/ && git reset --hard fa433e0
cd $PLUG_HOME/vim-tmux-navigator/ && git reset --hard d25c7eb
cd $PLUG_HOME/webapi-vim/ && git reset --hard a7789ab

