alias ls='ls -G'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# correct colors for tmux
alias tmux="TERM=screen-256color-bce tmux"

alias ls='gls --color=auto'

# easier cd movement
alias ..="cd .."
alias ..2="cd ../../"
alias ..3="cd ../../../"
