# enable color support of ls and also add handy aliases
eval "$(dircolors -b ~/.dir_colors)"
alias ls='ls -h --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# correct colors for tmux
alias tmux="TERM=screen-256color-bce tmux"

# easier cd movement
alias ..="cd .."
alias ..2="cd ../../"
alias ..3="cd ../../../"

alias psg="ps aux | grep"
