# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# Default editor
export EDITOR='vim'

if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

if [ -f ~/.funcs ]; then
    source ~/.funcs
fi
source ~/.shell_prompt.sh

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
